FROM flyway/flyway:latest

RUN mkdir -p /flyway/sql
COPY ./migrations/sql/V1__todo_app.up.sql /flyway/sql/V1__todo_app.up.sql

CMD flyway \
    -url=jdbc:$DATABASE_URL \
    -mixed=true \
    -connectRetries=60 migrate

